<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250514123302 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE notas (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, contenido TEXT DEFAULT NULL, fecha DATE NOT NULL, usuario_id INT NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_65776388DB38439E ON notas (usuario_id)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE notas ADD CONSTRAINT FK_65776388DB38439E FOREIGN KEY (usuario_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            ALTER TABLE notas DROP CONSTRAINT FK_65776388DB38439E
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE notas
        SQL);
    }
}
