<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250603121118 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE cliente (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nombre VARCHAR(255) NOT NULL, apellido1 VARCHAR(255) NOT NULL, apellido2 VARCHAR(255) NOT NULL, dni VARCHAR(15) DEFAULT NULL, referencia VARCHAR(255) DEFAULT NULL, fecha_creacion TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, direccion_id INT DEFAULT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX UNIQ_F41C9B257F8F253B ON cliente (dni)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX UNIQ_F41C9B25D0A7BD7 ON cliente (direccion_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE contrario (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nombre VARCHAR(255) NOT NULL, nif VARCHAR(20) DEFAULT NULL, direccion_id INT DEFAULT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX UNIQ_FFD95067ADE62BBB ON contrario (nif)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX UNIQ_FFD95067D0A7BD7 ON contrario (direccion_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE costas (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, estado VARCHAR(255) NOT NULL, fecha_tc DATE DEFAULT NULL, fecha15_tc DATE DEFAULT NULL, fecha_decreto DATE DEFAULT NULL, fecha20_decreto DATE DEFAULT NULL, importe DOUBLE PRECISION DEFAULT NULL, estado_cobro VARCHAR(255) NOT NULL, expediente_id INT DEFAULT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_BB5889554BF37E4E ON costas (expediente_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE direccion (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, calle VARCHAR(255) DEFAULT NULL, numero INT DEFAULT NULL, cp INT DEFAULT NULL, localidad VARCHAR(255) DEFAULT NULL, provincia VARCHAR(255) NOT NULL, pais VARCHAR(255) NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE documento (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nombre VARCHAR(255) NOT NULL, tipo VARCHAR(20) NOT NULL, ruta TEXT NOT NULL, fecha_subida DATE NOT NULL, expediente_id INT DEFAULT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_B6B12EC74BF37E4E ON documento (expediente_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE expediente (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, autos VARCHAR(20) DEFAULT NULL, estado VARCHAR(50) DEFAULT NULL, tipo_procedimiento VARCHAR(50) DEFAULT NULL, restitucion_economica VARCHAR(255) DEFAULT NULL, fecha_creacion TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, descripcion VARCHAR(150) DEFAULT NULL, contrario_id INT DEFAULT NULL, juzgado_id INT DEFAULT NULL, procurador_id INT DEFAULT NULL, cliente_id INT NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_D59CA4136E6D2F4E ON expediente (contrario_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_D59CA413B9A57363 ON expediente (juzgado_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_D59CA4132DBC7623 ON expediente (procurador_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_D59CA413DE734E51 ON expediente (cliente_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE juzgado (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nombre VARCHAR(255) NOT NULL, direccion_id INT DEFAULT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX UNIQ_695F140ED0A7BD7 ON juzgado (direccion_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE nota (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, contenido TEXT DEFAULT NULL, fecha DATE NOT NULL, usuario_id INT NOT NULL, cliente_id INT DEFAULT NULL, juzgado_id INT DEFAULT NULL, expediente_id INT DEFAULT NULL, costa_id INT DEFAULT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_C8D03E0DDB38439E ON nota (usuario_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_C8D03E0DDE734E51 ON nota (cliente_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_C8D03E0DB9A57363 ON nota (juzgado_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_C8D03E0D4BF37E4E ON nota (expediente_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_C8D03E0DDDC6F119 ON nota (costa_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE procurador (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nombre VARCHAR(255) NOT NULL, apellido1 VARCHAR(255) NOT NULL, apellido2 VARCHAR(255) NOT NULL, colegio VARCHAR(255) NOT NULL, numero_colegiado INT NOT NULL, direccion_id INT NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX UNIQ_30D459EDD0A7BD7 ON procurador (direccion_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(180) NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, active BOOLEAN NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_75EA56E0FB7336F0 ON messenger_messages (queue_name)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_75EA56E0E3BD61CE ON messenger_messages (available_at)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_75EA56E016BA31DB ON messenger_messages (delivered_at)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE cliente ADD CONSTRAINT FK_F41C9B25D0A7BD7 FOREIGN KEY (direccion_id) REFERENCES direccion (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE contrario ADD CONSTRAINT FK_FFD95067D0A7BD7 FOREIGN KEY (direccion_id) REFERENCES direccion (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE costas ADD CONSTRAINT FK_BB5889554BF37E4E FOREIGN KEY (expediente_id) REFERENCES expediente (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE documento ADD CONSTRAINT FK_B6B12EC74BF37E4E FOREIGN KEY (expediente_id) REFERENCES expediente (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE expediente ADD CONSTRAINT FK_D59CA4136E6D2F4E FOREIGN KEY (contrario_id) REFERENCES contrario (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE expediente ADD CONSTRAINT FK_D59CA413B9A57363 FOREIGN KEY (juzgado_id) REFERENCES juzgado (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE expediente ADD CONSTRAINT FK_D59CA4132DBC7623 FOREIGN KEY (procurador_id) REFERENCES procurador (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE expediente ADD CONSTRAINT FK_D59CA413DE734E51 FOREIGN KEY (cliente_id) REFERENCES cliente (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE juzgado ADD CONSTRAINT FK_695F140ED0A7BD7 FOREIGN KEY (direccion_id) REFERENCES direccion (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE nota ADD CONSTRAINT FK_C8D03E0DDB38439E FOREIGN KEY (usuario_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE nota ADD CONSTRAINT FK_C8D03E0DDE734E51 FOREIGN KEY (cliente_id) REFERENCES cliente (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE nota ADD CONSTRAINT FK_C8D03E0DB9A57363 FOREIGN KEY (juzgado_id) REFERENCES juzgado (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE nota ADD CONSTRAINT FK_C8D03E0D4BF37E4E FOREIGN KEY (expediente_id) REFERENCES expediente (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE nota ADD CONSTRAINT FK_C8D03E0DDDC6F119 FOREIGN KEY (costa_id) REFERENCES costas (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE procurador ADD CONSTRAINT FK_30D459EDD0A7BD7 FOREIGN KEY (direccion_id) REFERENCES direccion (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            ALTER TABLE cliente DROP CONSTRAINT FK_F41C9B25D0A7BD7
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE contrario DROP CONSTRAINT FK_FFD95067D0A7BD7
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE costas DROP CONSTRAINT FK_BB5889554BF37E4E
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE documento DROP CONSTRAINT FK_B6B12EC74BF37E4E
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE expediente DROP CONSTRAINT FK_D59CA4136E6D2F4E
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE expediente DROP CONSTRAINT FK_D59CA413B9A57363
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE expediente DROP CONSTRAINT FK_D59CA4132DBC7623
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE expediente DROP CONSTRAINT FK_D59CA413DE734E51
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE juzgado DROP CONSTRAINT FK_695F140ED0A7BD7
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE nota DROP CONSTRAINT FK_C8D03E0DDB38439E
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE nota DROP CONSTRAINT FK_C8D03E0DDE734E51
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE nota DROP CONSTRAINT FK_C8D03E0DB9A57363
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE nota DROP CONSTRAINT FK_C8D03E0D4BF37E4E
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE nota DROP CONSTRAINT FK_C8D03E0DDDC6F119
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE procurador DROP CONSTRAINT FK_30D459EDD0A7BD7
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE cliente
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE contrario
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE costas
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE direccion
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE documento
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE expediente
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE juzgado
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE nota
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE procurador
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE "user"
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE messenger_messages
        SQL);
    }
}
