<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250501191343 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE direccion (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, calle VARCHAR(255) DEFAULT NULL, numero INT DEFAULT NULL, cp INT DEFAULT NULL, localidad VARCHAR(255) DEFAULT NULL, provincia VARCHAR(255) NOT NULL, pais VARCHAR(255) NOT NULL, procurador_id INT NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_F384BE952DBC7623 ON direccion (procurador_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE procurador (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nombre VARCHAR(255) NOT NULL, apellido1 VARCHAR(255) NOT NULL, apellido2 VARCHAR(255) NOT NULL, colegio VARCHAR(255) NOT NULL, numero_colegiado INT NOT NULL, direccion_id INT NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE direccion ADD CONSTRAINT FK_F384BE952DBC7623 FOREIGN KEY (procurador_id) REFERENCES procurador (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            ALTER TABLE direccion DROP CONSTRAINT FK_F384BE952DBC7623
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE direccion
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE procurador
        SQL);
    }
}
