<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250516120212 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE expediente (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, autos VARCHAR(20) DEFAULT NULL, estado VARCHAR(50) DEFAULT NULL, tipo_procedimiento VARCHAR(50) DEFAULT NULL, restitucion_economica VARCHAR(255) DEFAULT NULL, fecha_creacion TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, contrario_id INT DEFAULT NULL, juzgado_id INT DEFAULT NULL, procurador_id INT DEFAULT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_D59CA4136E6D2F4E ON expediente (contrario_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_D59CA413B9A57363 ON expediente (juzgado_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_D59CA4132DBC7623 ON expediente (procurador_id)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE expediente ADD CONSTRAINT FK_D59CA4136E6D2F4E FOREIGN KEY (contrario_id) REFERENCES contrario (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE expediente ADD CONSTRAINT FK_D59CA413B9A57363 FOREIGN KEY (juzgado_id) REFERENCES juzgado (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE expediente ADD CONSTRAINT FK_D59CA4132DBC7623 FOREIGN KEY (procurador_id) REFERENCES procurador (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            ALTER TABLE expediente DROP CONSTRAINT FK_D59CA4136E6D2F4E
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE expediente DROP CONSTRAINT FK_D59CA413B9A57363
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE expediente DROP CONSTRAINT FK_D59CA4132DBC7623
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE expediente
        SQL);
    }
}
