<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250511181459 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE contrario (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nombre VARCHAR(255) NOT NULL, nif VARCHAR(20) DEFAULT NULL, direccion_id INT DEFAULT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_FFD95067D0A7BD7 ON contrario (direccion_id)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE contrario ADD CONSTRAINT FK_FFD95067D0A7BD7 FOREIGN KEY (direccion_id) REFERENCES direccion (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            ALTER TABLE contrario DROP CONSTRAINT FK_FFD95067D0A7BD7
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE contrario
        SQL);
    }
}
