<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250515115341 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE nota (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, contenido TEXT DEFAULT NULL, fecha DATE NOT NULL, usuario_id INT NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_C8D03E0DDB38439E ON nota (usuario_id)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE nota ADD CONSTRAINT FK_C8D03E0DDB38439E FOREIGN KEY (usuario_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE notas DROP CONSTRAINT fk_65776388db38439e
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE notas
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE notas (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, contenido TEXT DEFAULT NULL, fecha DATE NOT NULL, usuario_id INT NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX idx_65776388db38439e ON notas (usuario_id)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE notas ADD CONSTRAINT fk_65776388db38439e FOREIGN KEY (usuario_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE nota DROP CONSTRAINT FK_C8D03E0DDB38439E
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE nota
        SQL);
    }
}
